version: 2.1
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/android:api-28
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Install Fastlane
          command: bundle install
      - run:
          name: Download App Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Run Tests
          command: ./gradlew lint test
      - run:
          name: Print API Token
          command: echo LUMA_APPCENTER_OWNER_NAME
      - run:
          name: Print API Token with braces
          command: echo ${LUMA_APPCENTER_OWNER_NAME}
      - run:
          name: Print Control run
          command: echo "Something"
      - run:
          name: Upload to HockeyApp
          command: bundle exec fastlane assemble_release
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - store_test_results:
          path: app/build/test-results

workflows:
  version: 2.1
  build-and-deploy-workflow:
    jobs:
      - build:
          context: test-context