version: 2.1

defaults: &defaults
  docker:
    - image: circleci/android:api-28
  environment:
    JVM_OPTS: -Xmx3200m
  working_directory: ~/project

android_dependencies_cache_key: &android_dependencies_cache_key
  jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}

fastlane_dependencies_cache_key: &fastlane_dependencies_cache_key
  gems-{{ checksum "Gemfile.lock" }}

install_android_dependencies: &install_android_dependencies
  - restore_cache:
      key: *android_dependencies_cache_key
  - run:
      name: Install Android dependencies
      command: ./gradlew androidDependencies
  - save_cache:
      key: *android_dependencies_cache_key
      paths:
        - ~/.gradle

install_fastlane_dependencies: &install_fastlane_dependencies
  - restore_cache:
      key: *fastlane_dependencies_cache_key
  - run:
      name: Install Fastlane dependencies for deployment to App Center
      command: bundle install
  - save_cache:
      key: *fastlane_dependencies_cache_key
      paths:
        - vendor/bundle

only_for_develop_branch: &only_for_develop_branch
  filters:
    branches:
      only:
      - develop

jobs:
  run-unit-tests:
    <<: *defaults
    steps:
      - checkout
      - *install_android_dependencies
      - run:
          name: Run unit yests
          command: ./gradlew test #TODO: Run only one build type tests instead of all maybe?
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - store_test_results:
          path: app/build/test-results

  deploy-to-app-center:
    <<: *defaults
    steps:
      - checkout
      - *install_android_dependencies
      - *install_fastlane_dependencies
      - run:
          name: Decode Keystore for signing APK
          command: base64 --decode \<<< $SERVICE_PROVIDER_APP_APP_CENTER_ENCODED_KEYSTORE > app/serviceproviderapp.appcenter.keystore
      - run:
          name: Upload APK to App Center
          command: bundle exec fastlane assemble_release

workflows:
  version: 2.1
  test-and-deploy:
    jobs:
      - run-unit-tests:
          <<: *only_for_develop_branch
      - deploy-to-app-center:
          <<: *only_for_develop_branch
          context: deploy-service-provider-app-to-app-center
          requires:
            - run-unit-tests

