version: 2.1

defaults: &defaults
  docker:
    - image: circleci/android:api-28
  environment:
    JVM_OPTS: -Xmx3200m
  working_directory: ~/project

android_dependencies_cache_key: &android_dependencies_cache_key
  jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}

jobs:
  install-dependencies:
    <<: *defaults
    steps:
      - checkout
      - restore-cache:
          key: *android_dependencies_cache_key
      - run:
          name: Install Android dependencies
          command: ./gradlew androidDependencies
      - run:
          name: Install Fastlane dependencies for deployment to App Center
          command: bundle install
      - save_cache:
          key: *android_dependencies_cache_key
          paths:
          - ~/.gradle
      - persist_to_workspace:
          root: .
          path: .

  run-unit-tests:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/project
      - run:
          name: Run Unit Tests
          command: ./gradlew test

  deploy-to-app-center:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/project
      - run:
          name: Decode Keystore for Signing APK
          command: base64 -d <<< $SERVICE_PROVIDER_APP_APP_CENTER_ENCODED_KEYSTORE > ~/project/app/serviceproviderapp.appcenter.keystore
      - run:
          name: Upload APK to App Center
          command: bundle exec fastlane assemble_release
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - store_test_results:
          path: app/build/test-results

workflows:
  version: 2.1
  test-and-deploy:
    filters:
      branches:
        only:
          - develop
    jobs:
      - install-dependencies
      - run-unit-tests:
          requires:
            - install-dependencies
      - deploy-to-app-center:
          context: deploy-service-provider-app-to-app-center
          requires:
            - install-dependencies
            - run-unit-tests
