default_platform(:android)

platform :android do
  desc "Deploy build to AppCenter"
  lane :assemble_release do
    gradle(task: "clean assembleAppCenter")

    appcenter_upload(
      api_token: ENV["SERVICE_PROVIDER_APP_APP_CENTER_API_TOKEN"],
      owner_name: ENV["SERVICE_PROVIDER_APP_APP_CENTER_OWNER_NAME"],
      group: ENV["SERVICE_PROVIDER_APP_APP_CENTER_GROUP_NAME"],
      app_name: ENV["SERVICE_PROVIDER_APP_APP_CENTER_APP_NAME"],
      apk: lane_context[SharedValues::GRADLE_APK_OUTPUT_PATH]
    )
  end
end
